spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: echo
    url: jdbc:mysql://127.0.0.1:3306/jids?characterEncoding=utf8&autoReconnect=true&failOverReadOnly=false
server:
  port: 9000

logging:
  level:
    zliu.elliot.JointIntelligentDrillServer.dao: debug
mybatis:
  mapper-locations: classpath:/mappers/*.xml

